//action type
export const GET_PROFILE = "GET_PROFILE";
export const GET_LIST_POSTS = "GET_LIST_POSTS";
export const UPDATE_LIKE_POST = "UPDATE_LIKE_POST";
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const GET_LIST_FOLLOWERS = "GET_LIST_FOLLOWERS";
export const GET_LIST_FOLLOWINGS = "GET_LIST_FOLLOWINGS";
export const LOGIN = "LOGIN";
export const LOGIN_FAIL="LOGIN_FAIL";
export const MESS_ERR="ACCOUNT NOT EXIST OR PRIVATE KEY NOT CORRECT";
export const LOG_OUT="LOG_OUT";
export const CREATE_SUCCESS="CREATE_SUCCESS";
export const CREATE_FAIL="CREATE_FAIL";
export const OPEN_ACCOUNT="OPEN_ACCOUNT";
export const CLOSE_ACCOUNT="CLOSE_ACCOUNT";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const GET_PROFILE_NEW_FEED = "GET_PROFILE_NEW_FEED";
export const COUNT_MENU_TOP = "COUNT_MENU_TOP";
export const GET_INFO_PROFILE = "GET_INFO_PROFILE";
export const HEADER = "HEADER";


