//action type
export const GET_PROFILE = "GET_PROFILE";
export const GET_LIST_POSTS = "GET_LIST_POSTS";
export const UPDATE_LIKE_POST = "UPDATE_LIKE_POST";
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const GET_LIST_FOLLOWERS = "GET_LIST_FOLLOWERS";
export const GET_LIST_FOLLOWINGS = "GET_LIST_FOLLOWINGS";
